### ISSUE TITLE
Handle Prefix authorization should be possible with certificates.

### ISSUE THREAD

**Issue by Pfeil** [kit-data-manager/pit-service#1]
Currently, it is possible using username and password, which is discouraged. Requires a prefix so we can actually test everything properly.

**Comment by Pfeil** [comment]
@ThomasJejkal 
I am working on it. Should we keep the user+password functionality? I tend to throw it out because:
  - I would need to ask to also have a passphrase for our test prefix. We currently only have public/private keys, which is the better default.
  - I use the handle system java client to make things simple (https://handle.net/hnr-source/api-javadoc-v9.3.0/index.html) and at least the simple API does not support it. So I would need to figure out if I can hack it somehow together with the advanced possibilities or keep the current, manual way included (and request a password for our test prefix). Still, the technical documentation does not say that the user+password method is deprecated. It "just" does not seem very welcome.

On the other hand, institutes which have been using a passphase for a longer time might like it. I personally would encourage them to use the certificate method, as it is not a complicated move.

**Comment by ThomasJejkal** [comment]
Well, I would suggest to default to certificate authentication. What I did not get is whether the client allows for "reasonable easy" password authentication. If it's a big deal to use username+password with the client, e.g. one week of hacking, I would remove it or uncomment it for the case, that someone in future asks for it. Otherwise, I would leave it in.

**Comment by Pfeil** [comment]
At least the simple way (the HSAdapterFactory) does not provide another way besides using a private key (https://handle.net/hnr-source/api-javadoc-v9.3.0/net/handle/api/HSAdapterFactory.html). I am not sure yet if there is a way to hack it together with the library, but so far I haven't recognized any. Of course, I could keep the old code somehow and request a passphrase for testing later (or maybe it is possible that I set a password myself somehow...).

By the way it looks like there are filters and other validation possibilities using the client, but I guess as the PIT architecture uncouples this functionality from the concrete PID service, this will not really be useful to us.

**Comment by ThomasJejkal** [comment]
You may also check the original code of the PIT Service, which you can find here: https://github.com/rpidproject/RDA-PRAGMA-Data-Service/tree/master/pragmapit-ext

For special functionalities, if it makes sense, you can add custom configuration properties, which might be used by a special PID service but not by others.

**Comment by Pfeil** [comment]
Using the new property

```
pit.pidsystem.implementation = HANDLE_PROTOCOL
```

The new handle protocol implementation can be used, which supports certificate based authentication. Using this setting enables additional properties to set the required credentials, e.g. like this:

```
pit.pidsystem.handle-protocol.credentials.handleIdentifierPrefix = 21.T11981
pit.pidsystem.handle-protocol.credentials.userHandle = 21.T11981/USER01
pit.pidsystem.handle-protocol.credentials.privateKeyPath = ./21.T11981_USER01_300_privkey.bin
```

The passphrase for the key file can be set using an environment variable `handleProtocolPrivateKeyPassphrase`.
