### ISSUE TITLE
H2 DB + LOCAL PidSystem may cause unexpected errors

### ISSUE THREAD

**Issue by ThomasJejkal** [kit-data-manager/pit-service#135]
**Describe the bug**
In the default configuration. H2 is configured as datasource and LOCAL as PIDSystem. Creating a new FDO will cause an instance of `PidDatabaseObject` to be created and written to the configured database. In H2, ElementCollections seems to be stored in a single text column, which has a default size of 256 characters, whereas other DBMS, e.g. Postgres, use a separate table. For H2, this will result in an error (HTTP 409 is returned, which is wrong but currently worked on) if the sum of all characters in the PID record exceeds this limit and the operation is aborted. 

It may help to update the annotation at `entries` to

`@Column(columnDefinition="TEXT", length = 1000)`

but this was not tested, yet. Alternatively, switching to Postgres did help.

**Comment by Pfeil** [comment]
Discussion notes:

- [ ] Write a test to discover the issue
- [ ] Evaluate an appropriate fix. Extending the length sounds nice, but we also have to check how this affects/restricts then other database implementations. For example, the annotation might reduce the actual length for other database systems. This needs to be evaluated properly. In the worst case, we should provide a small note about the limitation of this database and consider using a different configuration recommendation for local implementations. We could evaluate SQLite support to make the setup easier, considering the local PID system is mostly meant for demonstrations and experimentation. We should in any case improve the documentation on production use, where one will likely want to consider another database system like Postgres.
- [ ] In https://github.com/kit-data-manager/pit-service/pull/125, see if we return an appropriate code in such cases (why 409 is being returned)

**Comment by Pfeil** [comment]
I can not reproduce the issue. Do you have the JSON from the record which could not be registered and maybe the database configuration used? Thanks!
