### ISSUE TITLE
Test the built-in JWT authorization

### ISSUE THREAD

**Issue by Pfeil** [kit-data-manager/pit-service#2]
A configuration should allow the service being restricted to authorized users.

**Comment by ThomasJejkal** [comment]
Don't you plan to use the JWT implementation coming from service-base? In that case, there is already the possibility to enable/disable authentication.

**Comment by Pfeil** [comment]
Thanks, I did not recognize that. I guess we should use it. I thought it was not working properly as we had this problem that it was not correctly displayed in the openapi description. So I guess we have to make sure it is

- active and working properly
- properly described in the openapi/swagger definition.

**Comment by dalito** [comment]
From the comments here I don't fully understand if JWT authorisation is already working (in 1.0). Could you clarify?

**Comment by Pfeil** [comment]
Thank you for your comment (also in the other issue). The JWT implementation is part of a common dependency (service-base) we develop and use in many of our services, and is known to work. I just was not sure if the configuration in the Typed PID Maker was complete and correct. I did verify it yesterday and while it works with the fix in #2, the PR will receive some documentation before I merge it and release a new version. The release will still probably happen this week.

We are currently investigating in a strategy to support more authentication systems. So far, we explicitly support KeyCloak and JWT. Other JWT systems may or may not work; we will update the documentation as soon as we have more details about this. Details on the current support will soon be in the documentation, as mentioned above. The documentation currently consists of the [application.properties example file](https://github.com/kit-data-manager/pit-service/blob/master/config/application.properties), the [readme](https://github.com/kit-data-manager/pit-service#readme) and our [webpage](https://kit-data-manager.github.io/webpage/typed-pid-maker/index.html), which includes an interactive [OpenAPI definition of the current release](https://kit-data-manager.github.io/webpage/typed-pid-maker/openapi.html) (also available locally at runtime for a specific version) and introductions to selected topics.

**Comment by dalito** [comment]
Thank you very much for the answer and the pointers. This was really just a question to understand if authorisation is supported and in the scope of this tool. But what you write sounds great.

**Comment by Pfeil** [comment]
You're welcome. If you have any other questions or issues, feel free to ask. For documentation: The fix for authorization is included in the new [v1.0.1 release](https://github.com/kit-data-manager/pit-service/releases/tag/v1.0.1).
